.. A file containing links and substitutions
.. vim: ft=rst

.. Python stuff
.. _numpy: http://www.numpy.org

.. Imaging stuff
.. _NIfTI format: http://nifti.nimh.nih.gov/nifti-1
.. _OpenFMRI data sets: https://www.openfmri.org/data-sets
.. _visual object recognition dataset:
   https://www.openfmri.org/dataset/ds000105
.. _Haxby dataset:
   https://www.openfmri.org/dataset/ds000105
.. _test retest dataset: https://www.openfmri.org/dataset/ds000114
.. _nibabel: http://nipy.org/nibabel
.. _scikit-image: http://scikit-image.org
.. _tutorial on convolution:
    http://practical-neuroimaging.github.io/on_convolution.html
.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+02014
